// Auto-generated domain list from yt-dlp test URLs — do not edit by hand.
// Sorted so binary_search works without a HashSet.
static SUPPORTED_DOMAINS: &[&str] = &[
    "10.com.au", "10play.com.au", "163.com", "17.live", "1news.co.nz", "1tv.ru",
    "1und1.tv", "20min.ch", "23video.com", "247sports.com", "24tv.ua", "2doc.nl",
    "2m.ma", "3cat.cat", "3qsdn.com", "3sat.de", "3speak.tv", "4tube.com",
    "5-tv.ru", "56.com", "6abc.com", "6play.fr", "7plus.com.au", "7sur7.be",
    "9gag.com", "9news.com.au", "9now.com.au", "abc.com", "abc.net.au",
    "abc7news.com", "abcotvs.com", "abema.tv", "academicearth.org",
    "academymel.online", "acast.com", "acfun.cn", "adobe.com", "adultswim.com",
    "aeon.co", "aetv.com", "aftenposten.no", "aftonbladet.se", "agalega.gal",
    "aha.video", "ahctv.com", "ai-radio.org", "aitube.kz", "aktualne.cz",
    "albertalacrossetv.com", "alibaba.com", "aliexpress.com", "aljazeera.net",
    "allocine.fr", "allstar.gg", "alphaporno.com", "altcensored.com",
    "alura.com.br", "amadeus.tv", "amara.org", "amazon.co.jp", "amazon.co.uk",
    "amazon.com", "amazon.es", "amazon.in", "amc.com", "americastestkitchen.com",
    "amica.it", "anchor.fm", "anderetijden.nl", "angel.com", "animalplanet.com",
    "animationdigitalnetwork.com", "ant1news.gr", "antenna.gr", "aol.ca",
    "aol.co.uk", "aol.com", "aol.de", "aol.jp", "apa.at", "aparat.com",
    "apple.com", "arbeitsagentur.de", "archive.org", "ardaudiothek.de",
    "ardmediathek.de", "ardsounds.de", "arnes.si", "art19.com", "arte.tv",
    "artstation.com", "asahitv.fi", "asiancrush.com", "asobistore.jp",
    "atlutd.com", "atresplayer.com", "atscaleconference.com",
    "audi-mediacenter.com", "audioboom.com", "audiodraft.com", "audiomack.com",
    "audius.co", "austinfc.com", "autoweek.nl", "b-ch.com", "backscreen.com",
    "bahry.com", "baidu.com", "banbye.com", "bandcamp.com", "bandlab.com",
    "banned.video", "barrons.com", "bbc.co.uk", "bbc.com", "bbcamerica.com",
    "bbcollab.com", "bbv-tv.net", "beacon.tv", "beatport.com", "beeg.com",
    "behindkink.com", "beltzlaw.com", "bet.com", "bfi.org.uk", "bfmtv.com",
    "bibeltv.de", "bigbrothercanada.ca", "bigo.tv", "bild.de", "bilibili.com",
    "bilibili.tv", "biliintl.com", "biobiochile.cl", "biography.com",
    "bitchute.com", "bitmovin.com", "bleacherreport.com", "blerp.com",
    "blogger.com", "bloomberg.com", "bndestem.nl", "bogmedia.org",
    "bongacams.com", "bongacams.net", "boosty.to", "bostonglobe.com", "box.com",
    "boxcast.tv", "bpb.de", "br-klassik.de", "br.de", "brainpop.com",
    "bravotv.com", "breezy.hr", "breitbart.com", "brightcove.com",
    "brightcove.net", "brilliantpala.org", "bsky.app", "bsky.dev", "bt.no",
    "btvplus.bg", "buffalobills.com", "bundesliga.com", "bundestag.de",
    "businessinsider.com", "businessinsider.com.pl", "businessinsider.nl",
    "buzzfeed.com", "bx1.be", "byutv.org", "c-span.org", "ca.gov", "calimero.tk",
    "cam4.com", "camfm.co.uk", "cammodels.com", "camsoda.com", "canal1.com.co",
    "canalalpha.ch", "canalc2.tv", "canalsurmas.es", "caracoltv.com", "castr.com",
    "cbc.ca", "cbs.com", "cbsnews.com", "cbssports.com", "cc.com", "ccc.de",
    "cctv.com", "cda.pl", "cellebrite.com", "ceskatelevize.cz", "cfmontreal.com",
    "cgtn.com", "channel4.com", "channel5.com", "charlierose.com",
    "chaturbate.com", "chaturbate.eu", "chaturbate.global", "chicagofirefc.com",
    "chiefs.com", "chilloutzone.net", "chorki.com", "cielotv.it", "cine.ar",
    "cinemax.com", "cinetecamilano.it", "cisco.com", "ciscolive.com", "cjsw.com",
    "clip.rs", "clipchamp.com", "closertotruth.com", "cloudflarestream.com",
    "cloudycdn.services", "clubdam.com", "clubic.com", "clyp.it", "cnbc.com",
    "cnevids.com", "cnn.com", "cnnindonesia.com", "cntv.cn", "co.il",
    "colbertlateshow.com", "coloradorapids.com", "columbuscrew.com",
    "conanclassic.com", "cookingchanneltv.com", "cookscountry.com",
    "cooksillustrated.com", "corriere.it", "coub.com", "cozy.tv", "cp24.com",
    "cpac.ca", "cpy.re", "cracked.com", "crackle.com", "craftsy.com",
    "croatian.film", "crooksandliars.com", "crowdbunker.com", "crtvg.es",
    "crunchyroll.com", "cts.com.tw", "ctv.ca", "ctvnews.ca", "cuatro.com",
    "cultureunplugged.com", "curiositystream.com", "cwseed.com", "cwtv.com",
    "cwtvpr.com", "cybrary.it", "d.tube", "dacast.com", "dagbladet.no", "dai.ly",
    "dailymail.co.uk", "dailymotion.com", "dailywire.com", "dangalplay.com",
    "daserste.de", "dashif.org", "daum.net", "daystar.tv", "dbtg.tv", "dctp.tv",
    "dcunited.com", "debian.social", "deezer.com", "democracynow.org",
    "destinationamerica.com", "deutschlandfunk.de", "dfb.de", "dhm.de", "di.se",
    "digitalconcerthall.com", "digitallyspeaking.com", "discogs.com",
    "discovery.com", "discoverylife.com", "discoveryplus.com",
    "discoveryplus.dk", "discoveryplus.es", "discoveryplus.fi",
    "discoveryplus.in", "discoveryplus.it", "discoveryplus.no",
    "discoveryplus.se", "disney.com", "disneychannel.ca", "disneychannel.de",
    "disneylatino.com", "disneyme.com", "disneynow.com", "disneyplus.com",
    "disneyturkiye.com.tr", "dispeak.com", "diynetwork.com", "dlive.tv",
    "dmax.de", "dood.to", "douyin.com", "douyu.com", "douyutv.com", "dplay.com",
    "dplay.dk", "dplay.fi", "dplay.jp", "dplay.no", "dplay.se", "dr-massive.com",
    "dr.dk", "dropbox.com", "dropout.tv", "drtalks.com", "drtuber.com",
    "dumpert.nl", "duoplay.ee", "dw.com", "dzen.ru", "ebaumsworld.com",
    "ebay.com", "een.be", "egghead.io", "eggs.mu", "elpais.com",
    "eltrecetv.com.ar", "embedly.com", "empflix.com", "epicon.in",
    "epidemicsound.com", "eplus.jp", "eporner.com", "erinn.biz", "erocast.me",
    "eroprofile.com", "err.ee", "ert.gr", "ertflix.gr", "espn.com",
    "espncricinfo.com", "espnfc.com", "espnfc.us", "etcanada.com", "ethnos.gr",
    "ettu.tv", "europa.eu", "europeantour.com", "eurosport.com",
    "eurosport.com.tr", "eurosport.de", "eurosport.dk", "eurosport.es",
    "eurosport.fr", "eurosport.hu", "eurosport.it", "eurosport.nl",
    "eurosport.no", "eurosport.ro", "euscreen.eu", "ewe.de", "expressen.se",
    "extra.cz", "facebook.com", "fancode.com", "fathom.video", "faz.net",
    "fc-zenit.ru", "fc2.com", "fccincinnati.com", "fcdallas.com", "fifa.com",
    "figureitoutbaseball.com", "filmarchiv.at", "filmarkivet.se", "filmon.com",
    "filmweb.no", "finna.fi", "fivethirtyeight.com", "flextv.co.kr", "flickr.com",
    "floatplane.com", "flowplayer.com", "foodnetwork.ca", "foodnetwork.com",
    "foodschmooze.org", "footyroom.com", "formula1.com", "fox.com", "fox9.com",
    "foxbusiness.com", "foxnews.com", "foxsports.com", "fptplay.vn",
    "framatube.org", "france.tv", "franceinfo.fr", "francetvinfo.fr",
    "freeform.com", "freesound.org", "freespeech.org", "freetv.com",
    "frontendmasters.com", "ft.dk", "fujitv.co.jp", "funk.net", "funker530.com",
    "fux.com", "fuyin.tv", "fxnetworks.com", "fyi.tv", "gab.com", "gaia.com",
    "gameclips.io", "gamedev.tv", "gamejolt.com", "gamepro.de", "gamespot.com",
    "gamestar.de", "gaskrank.tv", "gazeta.ru", "gazzetta.it", "gbnews.com",
    "gbnews.uk", "gdcvault.com", "gelderlander.nl", "gelocal.it", "genius.com",
    "geniuskitchen.com", "germanupa.de", "getcourse.io", "getcourse.ru",
    "gettr.com", "giantbomb.com", "githubusercontent.com", "glattvision.ch",
    "glide.me", "globalplayer.com", "globo.com", "glomex.com", "gmanetwork.com",
    "go.com", "godresource.com", "godtube.com", "gofile.io", "golem.de",
    "goodgame.ru", "google.com", "gopro.com", "gotostage.com", "gov.au",
    "gov.co", "gov.pl", "gq.com", "graspop.be", "gronkh.tv", "groupon.com",
    "h-its.org", "harpodeon.com", "hbo.com", "hclips.com", "hdzog.com",
    "hdzog.tube", "hearthis.at", "heise.de", "hellporno.com", "hellporno.net",
    "helsinkikanava.fi", "hessenschau.de", "hetklokhuis.nl", "hgtv.ca",
    "hgtv.com", "hidive.com", "hirado.hu", "historicfilms.com", "history.ca",
    "history.com", "historyvault.com", "hitrecord.org", "hockeycanada.ca",
    "hoichoi.tv", "hollywoodreporter.com", "holodex.net", "hotmovs.com",
    "hotmovs.tube", "hotnewhiphop.com", "hotstar.com", "houstondynamofc.com",
    "hr-fernsehen.de", "href.li", "hrt.hr", "hsbi.de", "hse.de", "huajiao.com",
    "huffingtonpost.com", "huffingtonpost.it", "hulu.com", "hungama.com",
    "huya.com", "hypem.com", "hypergryph.com", "hytale.com", "hyvinvointitv.fi",
    "ibm.com", "icareus.com", "idagio.com", "idnes.cz", "ifc.com", "iflix.com",
    "ign.com", "iheart.com", "iheartpodcastnetwork.com", "ilpost.it",
    "ilsecoloxix.it", "iltalehti.fi", "imdb.com", "imgur.com", "ina.fr",
    "inc.com", "indavideo.hu", "india.com", "indiedb.com", "inez.fi", "infoq.com",
    "inkryptvideos.com", "inporn.com", "instagram.com", "interfax.ru",
    "intermiamicf.com", "internazionale.it", "investigationdiscovery.com",
    "invidio.us", "invidious.io", "iol.pt", "iprima.cz", "iq.com", "iqiyi.com",
    "islamchannel.tv", "israelnationalnews.com", "itar-tass.com", "itpro.tv",
    "itv.com", "iu.edu", "ivi.ru", "ivi.tv", "ivideon.com", "ivoox.com",
    "iwara.tv", "ixigua.com", "jamendo.com", "jeuxvideo.com", "jiosaavn.com",
    "joj.sk", "jove.com", "joyn.de", "jtbc.co.kr", "jwplatform.com",
    "jwplayer.com", "kakao.com", "kaltura.com", "kankanews.com", "katsomo.fi",
    "kelbyone.com", "kenh14.vn", "khanacademy.org", "kick.com", "kicker.de",
    "kickstarter.com", "kika.de", "kinopoisk.ru", "knpb.org", "kommunetv.no",
    "kompas.com", "krasview.ru", "ksite.de", "kth.se", "ku6.com", "kuwo.cn",
    "kvs-demo.com", "kwikmotion.com", "la7.it", "ladigitale.dev", "lafc.com",
    "lagalaxy.com", "laracasts.com", "last.fm", "lastampa.it", "laxarxames.cat",
    "lbry.tv", "lci.fr", "lcp.fr", "le.com", "learningonscreen.ac.uk",
    "lecturio.com", "lecturio.de", "lefigaro.fr", "lego.com", "leitv.it",
    "lemonde.fr", "lenta.ru", "lequipe.fr", "lesports.com", "libsyn.com",
    "lidovky.cz", "life.ru", "lifetimemovieclub.com", "likee.video", "linkedin.com",
    "liputan6.com", "listennotes.com", "litv.tv", "livejournal.com",
    "livestream.com", "livestreamfails.com", "livr.jp", "lnk.lt", "loc.gov",
    "locipo.jp", "loco.com", "logo.de", "loom.com", "lovehomeporn.com", "lrt.lt",
    "lsm.lv", "lumni.fr", "m-net.de", "m4sport.hu", "magellantv.com",
    "magentamusik.de", "mail.ru", "manyvids.com", "maoritelevision.com",
    "markiza.sk", "marquee.tv", "marvelkids.com", "massengeschmack.tv",
    "masters.com", "matchi.tv", "matchtv.ru", "mave.digital", "mbc.net",
    "mbn.co.kr", "mdr.de", "mdstrm.com", "mech-plus.com", "medal.tv",
    "mediadelivery.net", "mediaite.com", "mediaklikk.hu", "mediaset.es",
    "mediaset.it", "mediasetinfinity.es", "mediasite.com", "mediaworks.nz",
    "medici.tv", "megaphone.fm", "megatv.com", "meipai.com", "melon.com",
    "metacritic.com", "metro.cz", "mewatch.sg", "mgtv.com", "microsoft.com",
    "minds.com", "minifiddlers.org", "mir24.tv", "mirrativ.com", "mirror.co.uk",
    "misis.ru", "mit.edu", "mixch.tv", "mixcloud.com", "mixlr.com", "mlb.com",
    "mlssoccer.com", "mojevideo.sk", "monstercat.com",
    "monumentalsportsnetwork.com", "motorsport.com", "moviefap.com",
    "moviepilot.de", "msn.com", "msnbc.com", "msvdn.net", "mtv.com", "mtv.fi",
    "mtvuutiset.fi", "mubi.com", "muenchen.tv", "mujrozhlas.cz", "murrtube.net",
    "muse.ai", "musescore.com", "mux.com", "mx3.ch", "mxplayer.in",
    "mycanal.fr", "mychannels.video", "mylifetime.com", "myspace.com",
    "myspass.de", "myvideo.ge", "myvidster.com", "mzaalo.com", "n-joy.de",
    "n-tv.de", "n1info.com", "n1info.rs", "n1info.si", "nascar.com",
    "nashvillesc.com", "nate.com", "nationalarchives.gov.uk",
    "nationalgeographic.com", "naver.com", "nba.com", "nbc.com", "nbcboston.com",
    "nbclosangeles.com", "nbcnews.com", "nbcolympics.com", "nbcsports.com",
    "ncpa-classic.com", "ndr.de", "ndtv.com", "nebula.tv", "nekohacker.com",
    "nelonenmedia.fi", "nest.com", "netapp.com", "netplus.tv", "netzkino.de",
    "newgrounds.com", "newspicks.com", "newsy.com", "newyorkredbulls.com",
    "nexx.cloud", "nexxcdn.com", "nfb.ca", "nfhsnetwork.com", "nfl.com",
    "nhk.or.jp", "nhl.com", "nick.com", "nico.ms", "nicochannel.jp",
    "nicovideo.jp", "ninaprotocol.com", "nintendo.com", "njpwworld.com",
    "nls.uk", "nluug.nl", "nobelprize.org", "noice.id", "nonktube.com",
    "noodlemagazine.com", "noovo.ca", "nos.nl", "nova.bg", "nova.cz", "nova.rs",
    "nowcanal.pt", "nowness.com", "nowtv.it", "noz.de", "npo.nl", "npo3.nl",
    "npostart.nl", "npr.org", "nrk.no", "nrksuper.no", "nrl.com", "ntnu.no",
    "ntr.nl", "nts.live", "ntv.co.jp", "ntv.ru", "nu.nl", "nubiles-porn.com",
    "nuvid.com", "nycfc.com", "nytimes.com", "nzherald.co.nz", "nzonscreen.com",
    "nzz.ch", "odysee.com", "of.tv", "ok.ru", "oktoberfest-tv.de", "olympics.com",
    "omnycontent.com", "omroepwnl.nl", "on24.com", "ondemandchina.com",
    "ondemandkorea.com", "onefootball.com", "onenews.co.nz", "onepeloton.com",
    "oneplace.com", "oneplus.ch", "onet.pl", "onet.tv", "onf.ca", "onsen.ag",
    "openrec.tv", "oppetarkiv.se", "oreilly.com", "orf.at", "orlandocitysc.com",
    "ortcam.com", "osnatel.de", "oth-regensburg.de", "outsidetv.com",
    "oxygen.com", "p3.no", "packtpub.com", "palcomp3.com", "palcomp3.com.br",
    "pandalive.co.kr", "panopto.com", "panopto.eu", "paramountplus.com",
    "paramountpressexpress.com", "parler.com", "parliamentlive.tv", "parti.com",
    "patreon.com", "pbs.org", "pbskids.org", "pbssocal.org", "pcmag.com",
    "peacocktv.com", "pearvideo.com", "peekvids.com", "peer.tv", "peertube.tv",
    "performgroup.com", "periscope.tv", "permanto.fi", "pgatour.com", "phihag.de",
    "philadelphiaunion.com", "philharmoniedeparis.fr", "philo.com", "phoenix.de",
    "photobucket.com", "pia-live.jp", "piapro.jp", "picarto.tv", "pieci.lv",
    "piksel.com", "piksel.tech", "pinkbike.com", "pinkbike.org", "pinterest.ca",
    "pinterest.com", "piwiplus.fr", "platzi.com", "play.tv", "player.fm",
    "playsuisse.ch", "playtvak.cz", "playvids.com", "plejada.pl", "pluralsight.com",
    "pluto.tv", "pm-wissen.com", "podbay.fm", "podchaser.com", "podomatic.com",
    "pokergo.com", "polsatgo.pl", "polskieradio.pl", "polskieradio24.pl",
    "popcorntimes.tv", "popcorntv.it", "pornbox.com", "pornerbros.com",
    "pornflip.com", "pornhub.com", "pornhub.net", "pornhub.org",
    "pornhubpremium.com", "pornotube.com", "pornovoisines.com", "pornoxo.com",
    "porntop.com", "porntube.com", "pps.tv", "pr0gramm.com", "prankcast.com",
    "premiershiprugby.com", "presstv.ir", "primevideo.com", "privatehomeclips.com",
    "projectveritas.com", "prx.org", "psu.edu", "puhutv.com", "pyvideo.org",
    "q-dance.com", "qingting.fm", "qq.com", "qtfm.cn", "quantum-tv.com",
    "qub.ca", "r7.com", "rad.live", "radiko.jp", "radio-canada.ca", "radio.de",
    "radio1.be", "radiofrance.fr", "radiojavan.com", "radiokapital.pl",
    "radiokierowcow.pl", "radioradicale.it", "radiozet.pl", "rai.it",
    "raicultura.it", "raiders.com", "rainews.it", "raiplay.it", "raiplaysound.it",
    "rakuten.co.jp", "raywenderlich.com", "rcs.it", "rctiplus.com", "rds.ca",
    "redbull.com", "redbull.tv", "redcdn.pl", "reddit.com", "redditmedia.com",
    "redgifs.com", "redtube.com", "redtube.com.br", "ren.tv", "repubblica.it",
    "restudy.dk", "retrocrush.tv", "reuters.com", "reverbnation.com",
    "revolutionsoccer.net", "rfi.fr", "ridehome.info", "rinse.fm",
    "rockstargames.com", "rokfin.com", "roosterteeth.com", "rottentomatoes.com",
    "roya.tv", "rozhlas.cz", "rsl.com", "rt.com", "rtbf.be", "rte.ie", "rtl.de",
    "rtl.hr", "rtl.lu", "rtl.nl", "rtl2.de", "rtlmost.hu", "rtlplay.be",
    "rtlxl.nl", "rtp.pt", "rtr.ch", "rtrfm.com.au", "rts.ch", "rtvcplay.co",
    "rtve.es", "rtvs.sk", "rtvslo.si", "rudo.video", "ruhr-uni-bochum.de",
    "rule34video.com", "rumble.com", "ruptly.tv", "rutube.ru", "ruutu.fi",
    "ruv.is", "s4c.cymru", "saavn.com", "sachsen.de", "safaribooksonline.com",
    "saitosan.net", "saktv.ch", "salt.ch", "samplefocus.com", "sandia.gov",
    "sangiin.go.jp", "sapo.pt", "sat7plus.org", "sauceplus.com", "sbnation.com",
    "sbs.co.kr", "sbs.com.au", "schooltv.nl", "sciebo.de", "sciencechannel.com",
    "screen9.com", "screen9.tv", "screencast-o-matic.com", "screencast.com",
    "screencastify.com", "screenrec.com", "scrolller.com", "sen.com",
    "senalcolombia.tv", "senate.gov", "seriesplus.com", "servus.com",
    "servustv.com", "sexu.com", "seznam.cz", "seznamzpravy.cz", "sharepoint.com",
    "shellac-archive.ch", "shemaroome.com", "shiey.com", "shooshtime.com",
    "showcase.ca", "showroom-live.com", "shugiintv.go.jp", "silenticetv.com",
    "simplecast.com", "sjearthquakes.com", "skaties.lv", "skeb.jp", "sky.com",
    "sky.it", "skylinewebcams.com", "skynews.com.au", "skynewsarabia.com",
    "skysports.com", "slideshare.net", "slideslive.com", "slutload.com",
    "smotrim.ru", "snagfilms.com", "snapchat.com", "softwhiteunderbelly.com",
    "sohu.com", "sonycrackle.com", "sonyliv.com", "sooplive.com", "soundcloud.com",
    "soundersfc.com", "soundgasm.net", "southpark.de", "southpark.lat",
    "southparkstudios.co.uk", "southparkstudios.com", "southparkstudios.com.br",
    "southparkstudios.nu", "sovietscloset.com", "spankbang.com", "spiegel.de",
    "sport1tv.ru", "sportbox.ru", "sporteurope.tv", "sportingkc.com",
    "sportschau.de", "sporza.be", "spotify.com", "spreaker.com", "sproutvideo.com",
    "sr-mediathek.de", "srf.ch", "stacommu.jp", "stage-plus.com", "startrek.com",
    "startv.com.tr", "starwars.com", "steamcommunity.com", "steampowered.com",
    "storyfire.com", "streaks.jp", "stream.cz", "stream.new", "streamable.com",
    "streetvoice.com", "stripchat.com", "stv.tv", "stvr.sk", "su.se",
    "subspla.sh", "subsplash.com", "substack.com", "suffolk.edu", "sundancetv.com",
    "sunporno.com", "supla.fi", "sverigesradio.se", "svt.se", "svtplay.se",
    "swipeto.pl", "swissinfo.ch", "syfy.com", "sztv.hu", "t-online.de", "t.me",
    "t13.cl", "tagesschau.de", "taptap.cn", "taptap.io", "tarangplus.in",
    "tass.ru", "tbs.co.jp", "tbs.com", "teachable.com", "teachertube.com",
    "teachingchannel.org", "teamcoco.com", "teamtreehouse.com", "ted.com",
    "tele-task.de", "tele5.de", "telebaern.tv", "telecaribe.co", "telecinco.es",
    "telegraaf.nl", "telemb.be", "telemundo.com", "telemundoarizona.com",
    "telequebec.tv", "televizeseznam.cz", "telewebion.com", "telezueri.ch",
    "telusoriginals.com", "telusworldofscienceedmonton.ca", "tennistv.com",
    "tf1.fr", "tf1info.fr", "tfo.org", "the-sun.com", "theater-complex.town",
    "thechosen.tv", "theepochtimes.com", "theguardian.com", "thehighwire.com",
    "theintercept.com", "theplatform.com", "thestar.com", "thesun.co.uk",
    "theverge.com", "thirteen.org", "thisamericanlife.org", "thisav.com",
    "thisoldhouse.com", "thisvid.com", "thumbzilla.com", "tiktok.com",
    "timbers.com", "tlc.com", "tlc.de", "tmz.com", "tnaflix.com", "tntdrama.com",
    "today.com", "toggle.sg", "toggo.de", "tokfm.pl", "toongoggles.com",
    "torontofc.ca", "tou.tv", "toutiao.com", "toypics.net", "travelchannel.com",
    "trovo.live", "trtworld.com", "trueid.id", "trueid.net", "trueid.ph",
    "trunews.com", "truthsocial.com", "trutv.com", "tsn.ca", "tube8.com",
    "tubepornclassic.com", "tubitv.com", "tudelft.nl", "tudou.com",
    "tuffhedemantv.com", "tugraz.at", "tum.de", "tum.live", "tumblr.com",
    "tun.in", "tunein.com", "tv2.no", "tv2bornholm.dk", "tv2east.dk", "tv2fyn.dk",
    "tv2kosmopol.dk", "tv2lorry.dk", "tv2nord.dk", "tv2ostjylland.dk",
    "tv2play.hu", "tv3.ee", "tv3.lt", "tv3play.ee", "tv4.se", "tv4play.se",
    "tv5monde.com", "tv5mondeplus.com", "tv5unis.ca", "tv8.it", "tvanouvelles.ca",
    "tvaplus.ca", "tvc.ru", "tver.jp", "tvigle.ru", "tvmidtvest.dk", "tvn24.pl",
    "tvn24bis.pl", "tvnoe.cz", "tvnoviny.sk", "tvnz.co.nz", "tvo.org",
    "tvopen.gr", "tvp.info", "tvp.pl", "tvplay.lv", "tvpparlament.pl",
    "tvpworld.com", "tvsyd.dk", "tvw.org", "tweakers.net", "twentythree.net",
    "twimg.com", "twitcasting.tv", "twitch.tv", "twitter.com", "txxx.com",
    "txxx.tube", "u-strasbg.fr", "udemy.com", "udn.com", "uib.no", "ukcolumn.org",
    "uliza.jp", "ulizaportal.jp", "ultimedia.com", "un.org", "unext.jp",
    "uni-hamburg.de", "uni-muenster.de", "unistra.fr", "united.cloud",
    "unity3d.com", "univ-sba.dz", "universal-music.de", "uol.com.br",
    "uplynk.com", "upornia.com", "upornia.tube", "upskillcourses.com",
    "urplay.se", "urskola.se", "usanetwork.com", "usatoday.com", "ustream.tv",
    "ustudio.com", "vanityfair.com", "varzesh3.com", "vbox7.com", "veo.co",
    "vevo.com", "vg.no", "vgtrk.com", "vgtv.no", "vh1.com", "vhcdn.com",
    "vice.com", "viceland.com", "vicetv.com", "vid.ly", "vid.plus", "viddler.com",
    "videa.hu", "videakid.hu", "videodelivery.net", "videoken.com",
    "videolectures.net", "videopress.com", "vidflex.tv", "vidio.com", "vidlii.com",
    "vids.io", "vidyard.com", "viki.com", "vimeo.com", "vimeopro.com", "viqeo.tv",
    "visir.is", "viu.com", "vjav.com", "vjav.tube", "vk.com", "vk.ru",
    "vkplay.live", "vkplay.ru", "vkvideo.ru", "voca.ro", "vocaroo.com",
    "vod-platform.net", "vod.pl", "voicy.jp", "volej.tv", "vootkids.com",
    "vox.com", "voyeurhit.com", "voyeurhit.tube", "vpro.nl", "vrt.be", "vtm.be",
    "vtv.vn", "vtvgo.vn", "vtxtv.ch", "vxxx.com", "w3.org", "waly.tv",
    "washingtonpost.com", "wat.tv", "watchnebula.com", "wch2016.com", "wdr.de",
    "wdrmaus.de", "weather.com", "webcamera.pl", "webcaster.pro", "webex.com",
    "webofstories.com", "weibo.cn", "weibo.com", "weiqitv.com",
    "weka-fachmedien.de", "wetv.com", "wetv.vip", "weverse.io", "wevidi.net",
    "whitecapsfc.com", "whowatch.tv", "whyp.it", "wikimedia.org", "wim.tv",
    "wimbledon.com", "winnersview.com", "winsports.co", "wired.com", "wistia.com",
    "wistia.net", "wordpress.com", "worldstarhiphop.com", "wp.pl",
    "wrestle-universe.com", "wsj.com", "wwe.com", "wyborcza.pl", "wykop.pl",
    "wysokieobcasy.pl", "x-minus.org", "x.com", "xboxclips.com", "xhamster.com",
    "xhamster.desi", "xhamster.one", "xhamster11.com", "xhamster2.com",
    "xhamster20.desi", "xhamster26.com", "xhday.com", "xhvid.com",
    "xiaohongshu.com", "ximalaya.com", "xinpianchang.com", "xnxx.com",
    "xnxx3.com", "xvideos.com", "xvideos.es", "xxxymovies.com", "yadi.sk",
    "yahoo.co.jp", "yahoo.com", "yandex.com", "yandex.ru", "yapfiles.ru",
    "yappy.media", "yfanefa.com", "yle.fi", "youix.com", "youjizz.com",
    "youku.com", "younow.com", "youporn.com", "youreporter.it", "youtu.be",
    "youtube.com", "youtubekids.com", "zaiko.io", "zapiks.com", "zapiks.fr",
    "zapp.nl", "zattoo.com", "zdf.de", "zdfheute.de", "zee5.com", "zenporn.com",
    "zetland.dk", "zhihu.com", "zing.vn", "zingmp3.vn", "zoom.us", "zwearz.com",
    "zype.com",
];

/// Returns true if the URL points directly to a media stream (m3u8/mpd/mp4).
/// These bypass the yt-dlp domain check — they're already resolved video URLs.
pub fn is_direct_media_url(url: &str) -> bool {
    let lower = url.to_lowercase();
    let path_end = lower.find('?').unwrap_or(lower.len());
    let path = &lower[..path_end];
    path.ends_with(".m3u8") || path.ends_with(".mpd") || path.ends_with(".mp4")
}

/// Returns true if the URL's domain is known to yt-dlp.
/// Checks from the most-specific suffix down so subdomains (music.youtube.com)
/// match their root (youtube.com) automatically.
pub fn is_supported_url(url: &str) -> bool {
    let host = match extract_host(url) {
        Some(h) => h,
        None => return false,
    };
    let parts: Vec<&str> = host.split('.').collect();
    // Walk from full host down to 2-part root, stopping before bare TLD
    for start in 0..parts.len().saturating_sub(1) {
        let candidate = parts[start..].join(".");
        if SUPPORTED_DOMAINS.binary_search(&candidate.as_str()).is_ok() {
            return true;
        }
    }
    false
}

fn extract_host(url: &str) -> Option<String> {
    // Strip scheme
    let rest = url.find("://").map(|i| &url[i + 3..])?;
    // Strip user:pass@
    let rest = rest.split('@').last()?;
    // Take until first / ? #
    let host = rest.split(|c| c == '/' || c == '?' || c == '#').next()?;
    // Strip port
    let host = host.split(':').next()?;
    if host.is_empty() {
        None
    } else {
        Some(host.to_lowercase())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accepts_known_sites() {
        assert!(is_supported_url("https://www.youtube.com/watch?v=abc"));
        assert!(is_supported_url("https://youtu.be/abc"));
        assert!(is_supported_url("https://music.youtube.com/watch?v=abc"));
        assert!(is_supported_url("https://clips.twitch.tv/abc"));
        assert!(is_supported_url("https://vimeo.com/123456"));
        assert!(is_supported_url("https://www.bilibili.com/video/BV1"));
        assert!(is_supported_url("https://www.bbc.co.uk/iplayer/episode/abc"));
        assert!(is_supported_url("https://x.com/user/status/123"));
    }

    #[test]
    fn rejects_unknown_sites() {
        assert!(!is_supported_url("https://bing.com/search?q=cats"));
        assert!(!is_supported_url("https://example.com/video.mp4"));
        assert!(!is_supported_url("https://randomsite.xyz/page"));
        assert!(!is_supported_url("not-a-url"));
        assert!(!is_supported_url(""));
    }
}
